### ISSUE TITLE
Remove implicit dependency on `NodeJS` namespace

### ISSUE THREAD

**Issue by blakeembrey** [types/npm-gulp#1]
This type definition is currently tightly coupled with the `node.d.ts` implementation details. It'd be better to get access to the correct types you need from the exported instances. For example:

``` ts
// Currently:
NodeJS.ReadWriteStream

// Use:
import { Tranform } from "stream"

Transform // Or whatever the correct stream instance actually is.
```

**Comment by unional** [comment]
That's a great idea.  Just that I don't know what it should be either. :smirk: Will commit a version and ask the glup guys. :smile:
